### register check
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"sumila",
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd",
    "role":"job_seeker"
}

### login check
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd"
}

### logout check
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJjb21wYW55IiwiaWF0IjoxNzc0OTI3MTU4LCJleHAiOjE3NzQ5Mjc3NTh9.Hsyr-tlm27AZlBRBmLaXm81-8oUAfGoOy3jOsZHE6NU

### get account check
GET http://localhost:3000/api/auth/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzc0NzY4NDk3LCJleHAiOjE3NzQ3NjkwOTd9.wr3oMpjLncPuCVlOlTofaHV_P3szzxT_agRPTdS5V4o

### get new access token
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json

{}

### company register check
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"google",
    "email":"google@gmail.com",
    "password":"g0Ogle!!",
    "role":"company"
}

### login check
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"google@gmail.com",
    "password":"g0Ogle!!"
}
