### register check
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"sumila",
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd",
    "role":"job_seeker"
}

### login check
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd"
}

### logout check
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzc3ODY2ODk2LCJleHAiOjE3Nzc4Njc0OTZ9.PQsRVKlfHWj-kynC0a5lzKHjsDJcroAxWJYuG3JCAC8

### get account check
GET http://localhost:3000/api/auth/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJjb21wYW55IiwiaWF0IjoxNzc3ODY3MTg4LCJleHAiOjE3Nzc4Njc3ODh9.MgJ5BmbioOV8iHfL64cH6EDpOyFnb5_nb8UC_FpGz-s

### get new access token
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json

{}

### company register check
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"google",
    "email":"google@gmail.com",
    "password":"g0Ogle!!",
    "role":"company"
}

### login check
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"google@gmail.com",
    "password":"g0Ogle!!"
}

### Second jobseeker
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"kumar",
    "email":"kumar123@gmail.com",
    "password":"P@ssw0rd",
    "role":"job_seeker"
}

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"kumar123@gmail.com",
    "password":"P@ssw0rd"
}

### deactivate user
DELETE http://localhost:3000/api/auth/deactivate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzc2MDU4NjIxLCJleHAiOjE3NzYwNTkyMjF9._om4nNwWoAm7AO0qWvALrUrQHSIY0QrZOgiehA7Y7Us 

### forget password
POST http://localhost:3000/api/auth/forget-password
Content-Type: application/json

{
    "email":"sumi123@gmail.com"
}

### reset password
POST http://localhost:3000/api/auth/reset-password?token=814cc3cf7fcaf4624834af80b864f0aa
Content-Type: application/json

{
    "password": "P@ssw0rd"
}

### verify email
POST http://localhost:3000/api/auth/verify-email?token=e6d028ec2058a53b854a985bee7576bd
Content-Type: application/json

{}
