### register check
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"sumila",
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd",
    "role":"job_seeker"
}

### login check
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd"
}

### logout check
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzc1MjI4MTY1LCJleHAiOjE3NzUyMjg3NjV9.LhJm8UFBBSoEHGBz0L0CSchdOtGF0GnNko9hUhi9EAQ

### get account check
GET http://localhost:3000/api/auth/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJjb21wYW55IiwiaWF0IjoxNzc1MjI4MDMxLCJleHAiOjE3NzUyMjg2MzF9.vpYYmuJP2f1q-FCU_JB0JWAi_l_-e0ZZZEdG84BI9Fo

### get new access token
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json

{}

### company register check
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"google",
    "email":"google@gmail.com",
    "password":"g0Ogle!!",
    "role":"company"
}

### login check
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"google@gmail.com",
    "password":"g0Ogle!!"
}

### Second jobseeker
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"kumar",
    "email":"kumar123@gmail.com",
    "password":"P@ssw0rd",
    "role":"job_seeker"
}

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"kumar123@gmail.com",
    "password":"P@ssw0rd"
}
