### post job
POST http://localhost:3000/api/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJjb21wYW55IiwiaWF0IjoxNzc0OTI3MTU4LCJleHAiOjE3NzQ5Mjc3NTh9.Hsyr-tlm27AZlBRBmLaXm81-8oUAfGoOy3jOsZHE6NU

{
    "title": "Backend developer",
    "deadlineDate": "2026-04-01",
    "requirement": ["Node JS","Typescript","MySQL"],
    "position": "junior",
    "employmentType": "intern",
    "workType": "on-site",
    "education": {
        "level": "Bachelor",
        "field": "CSIT"
    },
    "location": {
        "country": "Nepal",
        "city": "Ktm"
    },
    "salary": {
        "min": 10000,
        "max": 20000,
        "currency": "Rs."
    },
    "category": "Information and Technology"
}

### get all posted jobs
GET http://localhost:3000/api/jobs/myJobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJjb21wYW55IiwiaWF0IjoxNzc0OTI3MTU4LCJleHAiOjE3NzQ5Mjc3NTh9.Hsyr-tlm27AZlBRBmLaXm81-8oUAfGoOy3jOsZHE6NU

### get the job details
GET http://localhost:3000/api/jobs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJjb21wYW55IiwiaWF0IjoxNzc0NzY4Mzc2LCJleHAiOjE3NzQ3Njg5NzZ9.jLAhli56XtBxuxi1dywFimoarBiFOkZYb_aEeRhBzSQ

### view jobs
GET http://localhost:3000/api/jobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzc0OTI3MjMwLCJleHAiOjE3NzQ5Mjc4MzB9.8Pyx1BYGvQVmo2VzpMUi3diZgBJuD9Bf_PapqyhKi2I

### delete job
DELETE http://localhost:3000/api/jobs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJjb21wYW55IiwiaWF0IjoxNzc0NzY4ODkzLCJleHAiOjE3NzQ3Njk0OTN9.dKvIH34TSjgrdzmVMM7Mvs60RkWumtcU70SDQ-U8HjA