### get my profile route
GET http://localhost:3000/api/profile/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzc1MjI3NzY2LCJleHAiOjE3NzUyMjgzNjZ9.AA6Mhlt_q0t90S_ddy2GNsc9FlFWWjVKIYO2xPPvmHI

### get company profile route
GET  http://localhost:3000/api/profile/company/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJjb21wYW55IiwiaWF0IjoxNzc0NzY4MTk3LCJleHAiOjE3NzQ3Njg3OTd9.FOl8Oma7HoRTgsXc3ps8ksX-p5XPrkohVGBX7Gdh1c0

### view Job Seeker public profile route
GET http://localhost:3000/api/profile/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJjb21wYW55IiwiaWF0IjoxNzc0NzY4Mzc2LCJleHAiOjE3NzQ3Njg5NzZ9.jLAhli56XtBxuxi1dywFimoarBiFOkZYb_aEeRhBzSQ

### view Company public profile route
GET http://localhost:3000/api/profile/company/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzc0NzY4NDk3LCJleHAiOjE3NzQ3NjkwOTd9.wr3oMpjLncPuCVlOlTofaHV_P3szzxT_agRPTdS5V4o

### update Company profile route
PATCH http://localhost:3000/api/profile/company/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJjb21wYW55IiwiaWF0IjoxNzczNzQwNjc5LCJleHAiOjE3NzM3NDEyNzl9.GAPICVn5Y5DxHFnohYXIS_4GxskzUjdV_MwRTK61Zc0

{
    "aboutUs": "Google is a great company",
    "specialties": ["nodejs","typescript"],
    "hqLocation": { "country": "America", "city": "New York"},
    "contactNo": "01-12345346"

}
