### register check
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"sumila",
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd",
    "role":"job_seeker"
}

### login check
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd"
}

### logout check
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzczNTc1NzYyLCJleHAiOjE3NzM1NzYzNjJ9.5V3QVLk9EqJnj3s6fCZXOa6lHL8qOlPtIltCDfKmRJQ
{}

### get account check
GET http://localhost:3000/api/auth/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzczNTc1NzYyLCJleHAiOjE3NzM1NzYzNjJ9.5V3QVLk9EqJnj3s6fCZXOa6lHL8qOlPtIltCDfKmRJQ

### get new access token
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json

{}
