### get my profile route
GET http://localhost:3000/api/profile/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzczNjQzNDcxLCJleHAiOjE3NzM2NDQwNzF9.hn_Cs8MG9GZCml-6_jGUwehr7sMSnE7z5UGUSnJ1Y5w